In [1]:
import pandas as pd
import numpy as np

In [3]:
from pathlib import Path

file_path = Path("../Data/cleaned_loan_dataset.csv")

In [4]:
df = pd.read_csv(file_path)

In [4]:
print(f"Dataset Shape: {df.shape}")

Dataset Shape: (614, 13)

In [5]:
df.head()

,Customer_ID,Gender,Married,Dependents,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,569,Female,No,0,Graduate,No,2378,0.0,9,360,1,Urban,N
1,15,Male,Yes,2,Graduate,No,1299,1086.0,17,120,1,Urban,Y
2,95,Male,No,0,Not Graduate,No,3620,0.0,25,120,1,Semiurban,Y
3,134,Male,Yes,0,Graduate,Yes,3459,0.0,25,120,1,Semiurban,Y
4,556,Male,Yes,1,Graduate,No,5468,1032.0,26,360,1,Semiurban,Y

In [6]:
df.tail()

,Customer_ID,Gender,Married,Dependents,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
609,480,Male,Yes,2,Graduate,No,2947,1603.0,10,360,1,Urban,N
610,525,Male,No,0,Graduate,No,4680,2087.0,15,360,1,Semiurban,N
611,551,Male,Yes,2,Graduate,Yes,6633,0.0,25,360,0,Rural,N
612,552,Male,Yes,1,Not Graduate,No,2492,2375.0,30,360,1,Rural,Y
613,606,Male,Yes,0,Not Graduate,No,2400,3800.0,25,180,1,Urban,N

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         614 non-null    int64
 1   Gender              614 non-null    object
 2   Married             614 non-null    object
 3   Dependents          614 non-null    int64
 4   Education           614 non-null    object
 5   Self_Employed       614 non-null    object
 6   Applicant_Income    614 non-null    int64
 7   Coapplicant_Income  614 non-null    float64
 8   Loan_Amount         614 non-null    int64
 9   Loan_Amount_Term    614 non-null    int64
 10  Credit_History      614 non-null    int64
 11  Property_Area       614 non-null    object
 12  Loan_Status         614 non-null    object
dtypes: float64(1), int64(6), object(6)
memory usage: 62.5+ KB

In [8]:
missing_values = df.isnull().sum()
print("Missing Values per Column:\n", missing_values[missing_values > 0])

Missing Values per Column:
 Series([], dtype: int64)

In [9]:
duplicate_count = df.duplicated().sum()
print(f"\nTotal Duplicate Records: {duplicate_count}")

Total Duplicate Records: 0

In [10]:
categorical_cols = df.select_dtypes(include=['object', 'category']).columns

In [11]:
for col in categorical_cols:
    print(f"\n--- {col} ---")
    print(f"Unique Categories: {df[col].nunique()}")
    print(df[col].value_counts(dropna=False))

--- Gender ---
Unique Categories: 2
Gender
Male      499
Female    115
Name: count, dtype: int64

--- Married ---
Unique Categories: 2
Married
Yes    399
No     215
Name: count, dtype: int64

--- Education ---
Unique Categories: 2
Education
Graduate        480
Not Graduate    134
Name: count, dtype: int64

--- Self_Employed ---
Unique Categories: 2
Self_Employed
No     523
Yes     91
Name: count, dtype: int64

--- Property_Area ---
Unique Categories: 3
Property_Area
Semiurban    233
Urban        202
Rural        179
Name: count, dtype: int64

--- Loan_Status ---
Unique Categories: 2
Loan_Status
Y    422
N    192
Name: count, dtype: int64

In [12]:
target = 'Loan_Status'

numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
if target in numerical_cols:
    numerical_cols.remove(target)

categorical_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()
if target in categorical_cols:
    categorical_cols.remove(target)

print("Target Variable:", target)
print("Numerical Columns:", numerical_cols)
print("Categorical Columns:", categorical_cols)

Target Variable: Loan_Status
Numerical Columns: ['Customer_ID', 'Dependents', 'Applicant_Income', 'Coapplicant_Income', 'Loan_Amount', 'Loan_Amount_Term', 'Credit_History']
Categorical Columns: ['Gender', 'Married', 'Education', 'Self_Employed', 'Property_Area']